version: '3'

services:

  redis2018_user:
    image: 61.163.79.140:8000/redis:3.2.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/db/redis/redis_user:/var/lib/redis/6379 
      - /data/db/redis/log/redis_user:/var/log/redis 
      - /data/db/redis/redis.conf:/etc/redis/6379.conf
    hostname: redis2018_user
    ports:
      - 127.0.0.1:10001:6379
    networks: 
      - develop
    restart: unless-stopped

  redis2018_cache:
    image: 61.163.79.140:8000/redis:3.2.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/db/redis/redis_cache:/var/lib/redis/6379
      - /data/db/redis/log/redis_cache:/var/log/redis
      - /data/db/redis/redis.conf:/etc/redis/6379.conf
    hostname: redis2018_cache
    ports:
      - 127.0.0.1:10002:6379
    networks: 
      - develop
    restart: unless-stopped
    environment:
      - TERM=linux

  redis2018_datalock:
    image: 61.163.79.140:8000/redis:3.2.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/db/redis/redis_datalock:/var/lib/redis/6379
      - /data/db/redis/log/redis_datalock:/var/log/redis
      - /data/db/redis/redis.conf:/etc/redis/6379.conf
    hostname: redis2018_datalock
    ports:
      - 127.0.0.1:10003:6379
    networks: 
      - develop
    restart: unless-stopped
    environment:
      - TERM=linux

  postgresql:
    image: 61.163.79.140:8000/postgresql-94
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/db/postgresql:/var/lib/pgsql
    hostname: postgresql
    ports:
      - 127.0.0.1:10031:5432 
      - 172.21.0.15:10031:5432
    networks: 
      - develop
    restart: unless-stopped
    environment:
      - TERM=linux

  mongodb:
    image: 61.163.79.140:8000/mongodb-2.6.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/db/mongo/config:/home/mongodb-linux-x86_64-2.6.4/bin/config
      - /data/db/mongo/db:/data/db
      - /data/db/mongo/logs:/data/logs 
    hostname: mongodb
    ports:
      - 127.0.0.1:10021:27101 
      - 172.21.0.15:10021:27101
    networks: 
      - develop
    restart: unless-stopped
    environment:
      - TERM=linux

networks: 
  develop:
    external:
      name: develop

